// Code generated by ent, DO NOT EDIT.

package user

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the user type in the database.
	Label = "user"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldUsername holds the string denoting the username field in the database.
	FieldUsername = "username"
	// FieldAge holds the string denoting the age field in the database.
	FieldAge = "age"
	// FieldEmail holds the string denoting the email field in the database.
	FieldEmail = "email"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldSalt holds the string denoting the salt field in the database.
	FieldSalt = "salt"
	// FieldHash holds the string denoting the hash field in the database.
	FieldHash = "hash"
	// FieldVerifiedEmail holds the string denoting the verified_email field in the database.
	FieldVerifiedEmail = "verified_email"
	// EdgeMailVerif holds the string denoting the mail_verif edge name in mutations.
	EdgeMailVerif = "mail_verif"
	// EdgeFriendships holds the string denoting the friendships edge name in mutations.
	EdgeFriendships = "friendships"
	// EdgeFriendOf holds the string denoting the friend_of edge name in mutations.
	EdgeFriendOf = "friend_of"
	// Table holds the table name of the user in the database.
	Table = "users"
	// MailVerifTable is the table that holds the mail_verif relation/edge.
	MailVerifTable = "mail_verifs"
	// MailVerifInverseTable is the table name for the MailVerif entity.
	// It exists in this package in order to avoid circular dependency with the "mailverif" package.
	MailVerifInverseTable = "mail_verifs"
	// MailVerifColumn is the table column denoting the mail_verif relation/edge.
	MailVerifColumn = "user_id"
	// FriendshipsTable is the table that holds the friendships relation/edge.
	FriendshipsTable = "friendships"
	// FriendshipsInverseTable is the table name for the Friendship entity.
	// It exists in this package in order to avoid circular dependency with the "friendship" package.
	FriendshipsInverseTable = "friendships"
	// FriendshipsColumn is the table column denoting the friendships relation/edge.
	FriendshipsColumn = "user_friendships"
	// FriendOfTable is the table that holds the friend_of relation/edge.
	FriendOfTable = "friendships"
	// FriendOfInverseTable is the table name for the Friendship entity.
	// It exists in this package in order to avoid circular dependency with the "friendship" package.
	FriendOfInverseTable = "friendships"
	// FriendOfColumn is the table column denoting the friend_of relation/edge.
	FriendOfColumn = "user_friend_of"
)

// Columns holds all SQL columns for user fields.
var Columns = []string{
	FieldID,
	FieldUsername,
	FieldAge,
	FieldEmail,
	FieldCreatedAt,
	FieldSalt,
	FieldHash,
	FieldVerifiedEmail,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// UsernameValidator is a validator for the "username" field. It is called by the builders before save.
	UsernameValidator func(string) error
	// AgeValidator is a validator for the "age" field. It is called by the builders before save.
	AgeValidator func(int) error
	// EmailValidator is a validator for the "email" field. It is called by the builders before save.
	EmailValidator func(string) error
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultVerifiedEmail holds the default value on creation for the "verified_email" field.
	DefaultVerifiedEmail bool
)

// OrderOption defines the ordering options for the User queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByUsername orders the results by the username field.
func ByUsername(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUsername, opts...).ToFunc()
}

// ByAge orders the results by the age field.
func ByAge(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAge, opts...).ToFunc()
}

// ByEmail orders the results by the email field.
func ByEmail(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldEmail, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// BySalt orders the results by the salt field.
func BySalt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSalt, opts...).ToFunc()
}

// ByHash orders the results by the hash field.
func ByHash(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldHash, opts...).ToFunc()
}

// ByVerifiedEmail orders the results by the verified_email field.
func ByVerifiedEmail(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldVerifiedEmail, opts...).ToFunc()
}

// ByMailVerifField orders the results by mail_verif field.
func ByMailVerifField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newMailVerifStep(), sql.OrderByField(field, opts...))
	}
}

// ByFriendshipsCount orders the results by friendships count.
func ByFriendshipsCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newFriendshipsStep(), opts...)
	}
}

// ByFriendships orders the results by friendships terms.
func ByFriendships(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newFriendshipsStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}

// ByFriendOfCount orders the results by friend_of count.
func ByFriendOfCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newFriendOfStep(), opts...)
	}
}

// ByFriendOf orders the results by friend_of terms.
func ByFriendOf(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newFriendOfStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}
func newMailVerifStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(MailVerifInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2O, false, MailVerifTable, MailVerifColumn),
	)
}
func newFriendshipsStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(FriendshipsInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, FriendshipsTable, FriendshipsColumn),
	)
}
func newFriendOfStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(FriendOfInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, FriendOfTable, FriendOfColumn),
	)
}
