// Code generated by ent, DO NOT EDIT.

package ent

import (
	"backend/ent/game"
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
)

// Game is the model entity for the Game schema.
type Game struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// TimeStamp holds the value of the "time_stamp" field.
	TimeStamp time.Time `json:"time_stamp,omitempty"`
	// Type holds the value of the "type" field.
	Type string `json:"type,omitempty"`
	// NbPlayer holds the value of the "nb_player" field.
	NbPlayer int `json:"nb_player,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the GameQuery when eager-loading is set.
	Edges        GameEdges `json:"edges"`
	selectValues sql.SelectValues
}

// GameEdges holds the relations/edges for other nodes in the graph.
type GameEdges struct {
	// Results holds the value of the results edge.
	Results []*Result `json:"results,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// ResultsOrErr returns the Results value or an error if the edge
// was not loaded in eager-loading.
func (e GameEdges) ResultsOrErr() ([]*Result, error) {
	if e.loadedTypes[0] {
		return e.Results, nil
	}
	return nil, &NotLoadedError{edge: "results"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Game) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case game.FieldID, game.FieldNbPlayer:
			values[i] = new(sql.NullInt64)
		case game.FieldType:
			values[i] = new(sql.NullString)
		case game.FieldTimeStamp:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Game fields.
func (_m *Game) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case game.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int(value.Int64)
		case game.FieldTimeStamp:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field time_stamp", values[i])
			} else if value.Valid {
				_m.TimeStamp = value.Time
			}
		case game.FieldType:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field type", values[i])
			} else if value.Valid {
				_m.Type = value.String
			}
		case game.FieldNbPlayer:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field nb_player", values[i])
			} else if value.Valid {
				_m.NbPlayer = int(value.Int64)
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the Game.
// This includes values selected through modifiers, order, etc.
func (_m *Game) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryResults queries the "results" edge of the Game entity.
func (_m *Game) QueryResults() *ResultQuery {
	return NewGameClient(_m.config).QueryResults(_m)
}

// Update returns a builder for updating this Game.
// Note that you need to call Game.Unwrap() before calling this method if this Game
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *Game) Update() *GameUpdateOne {
	return NewGameClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the Game entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *Game) Unwrap() *Game {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: Game is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *Game) String() string {
	var builder strings.Builder
	builder.WriteString("Game(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("time_stamp=")
	builder.WriteString(_m.TimeStamp.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("type=")
	builder.WriteString(_m.Type)
	builder.WriteString(", ")
	builder.WriteString("nb_player=")
	builder.WriteString(fmt.Sprintf("%v", _m.NbPlayer))
	builder.WriteByte(')')
	return builder.String()
}

// Games is a parsable slice of Game.
type Games []*Game
