// Code generated by ent, DO NOT EDIT.

package ent

import (
	"backend/ent/game"
	"backend/ent/predicate"
	"backend/ent/result"
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// GameUpdate is the builder for updating Game entities.
type GameUpdate struct {
	config
	hooks    []Hook
	mutation *GameMutation
}

// Where appends a list predicates to the GameUpdate builder.
func (_u *GameUpdate) Where(ps ...predicate.Game) *GameUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetTimeStamp sets the "time_stamp" field.
func (_u *GameUpdate) SetTimeStamp(v time.Time) *GameUpdate {
	_u.mutation.SetTimeStamp(v)
	return _u
}

// SetNillableTimeStamp sets the "time_stamp" field if the given value is not nil.
func (_u *GameUpdate) SetNillableTimeStamp(v *time.Time) *GameUpdate {
	if v != nil {
		_u.SetTimeStamp(*v)
	}
	return _u
}

// SetType sets the "type" field.
func (_u *GameUpdate) SetType(v string) *GameUpdate {
	_u.mutation.SetType(v)
	return _u
}

// SetNillableType sets the "type" field if the given value is not nil.
func (_u *GameUpdate) SetNillableType(v *string) *GameUpdate {
	if v != nil {
		_u.SetType(*v)
	}
	return _u
}

// SetNbPlayer sets the "nb_player" field.
func (_u *GameUpdate) SetNbPlayer(v int) *GameUpdate {
	_u.mutation.ResetNbPlayer()
	_u.mutation.SetNbPlayer(v)
	return _u
}

// SetNillableNbPlayer sets the "nb_player" field if the given value is not nil.
func (_u *GameUpdate) SetNillableNbPlayer(v *int) *GameUpdate {
	if v != nil {
		_u.SetNbPlayer(*v)
	}
	return _u
}

// AddNbPlayer adds value to the "nb_player" field.
func (_u *GameUpdate) AddNbPlayer(v int) *GameUpdate {
	_u.mutation.AddNbPlayer(v)
	return _u
}

// AddResultIDs adds the "results" edge to the Result entity by IDs.
func (_u *GameUpdate) AddResultIDs(ids ...int) *GameUpdate {
	_u.mutation.AddResultIDs(ids...)
	return _u
}

// AddResults adds the "results" edges to the Result entity.
func (_u *GameUpdate) AddResults(v ...*Result) *GameUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddResultIDs(ids...)
}

// Mutation returns the GameMutation object of the builder.
func (_u *GameUpdate) Mutation() *GameMutation {
	return _u.mutation
}

// ClearResults clears all "results" edges to the Result entity.
func (_u *GameUpdate) ClearResults() *GameUpdate {
	_u.mutation.ClearResults()
	return _u
}

// RemoveResultIDs removes the "results" edge to Result entities by IDs.
func (_u *GameUpdate) RemoveResultIDs(ids ...int) *GameUpdate {
	_u.mutation.RemoveResultIDs(ids...)
	return _u
}

// RemoveResults removes "results" edges to Result entities.
func (_u *GameUpdate) RemoveResults(v ...*Result) *GameUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveResultIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *GameUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *GameUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *GameUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *GameUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

func (_u *GameUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	_spec := sqlgraph.NewUpdateSpec(game.Table, game.Columns, sqlgraph.NewFieldSpec(game.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.TimeStamp(); ok {
		_spec.SetField(game.FieldTimeStamp, field.TypeTime, value)
	}
	if value, ok := _u.mutation.GetType(); ok {
		_spec.SetField(game.FieldType, field.TypeString, value)
	}
	if value, ok := _u.mutation.NbPlayer(); ok {
		_spec.SetField(game.FieldNbPlayer, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedNbPlayer(); ok {
		_spec.AddField(game.FieldNbPlayer, field.TypeInt, value)
	}
	if _u.mutation.ResultsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   game.ResultsTable,
			Columns: []string{game.ResultsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(result.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedResultsIDs(); len(nodes) > 0 && !_u.mutation.ResultsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   game.ResultsTable,
			Columns: []string{game.ResultsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(result.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ResultsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   game.ResultsTable,
			Columns: []string{game.ResultsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(result.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{game.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// GameUpdateOne is the builder for updating a single Game entity.
type GameUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *GameMutation
}

// SetTimeStamp sets the "time_stamp" field.
func (_u *GameUpdateOne) SetTimeStamp(v time.Time) *GameUpdateOne {
	_u.mutation.SetTimeStamp(v)
	return _u
}

// SetNillableTimeStamp sets the "time_stamp" field if the given value is not nil.
func (_u *GameUpdateOne) SetNillableTimeStamp(v *time.Time) *GameUpdateOne {
	if v != nil {
		_u.SetTimeStamp(*v)
	}
	return _u
}

// SetType sets the "type" field.
func (_u *GameUpdateOne) SetType(v string) *GameUpdateOne {
	_u.mutation.SetType(v)
	return _u
}

// SetNillableType sets the "type" field if the given value is not nil.
func (_u *GameUpdateOne) SetNillableType(v *string) *GameUpdateOne {
	if v != nil {
		_u.SetType(*v)
	}
	return _u
}

// SetNbPlayer sets the "nb_player" field.
func (_u *GameUpdateOne) SetNbPlayer(v int) *GameUpdateOne {
	_u.mutation.ResetNbPlayer()
	_u.mutation.SetNbPlayer(v)
	return _u
}

// SetNillableNbPlayer sets the "nb_player" field if the given value is not nil.
func (_u *GameUpdateOne) SetNillableNbPlayer(v *int) *GameUpdateOne {
	if v != nil {
		_u.SetNbPlayer(*v)
	}
	return _u
}

// AddNbPlayer adds value to the "nb_player" field.
func (_u *GameUpdateOne) AddNbPlayer(v int) *GameUpdateOne {
	_u.mutation.AddNbPlayer(v)
	return _u
}

// AddResultIDs adds the "results" edge to the Result entity by IDs.
func (_u *GameUpdateOne) AddResultIDs(ids ...int) *GameUpdateOne {
	_u.mutation.AddResultIDs(ids...)
	return _u
}

// AddResults adds the "results" edges to the Result entity.
func (_u *GameUpdateOne) AddResults(v ...*Result) *GameUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddResultIDs(ids...)
}

// Mutation returns the GameMutation object of the builder.
func (_u *GameUpdateOne) Mutation() *GameMutation {
	return _u.mutation
}

// ClearResults clears all "results" edges to the Result entity.
func (_u *GameUpdateOne) ClearResults() *GameUpdateOne {
	_u.mutation.ClearResults()
	return _u
}

// RemoveResultIDs removes the "results" edge to Result entities by IDs.
func (_u *GameUpdateOne) RemoveResultIDs(ids ...int) *GameUpdateOne {
	_u.mutation.RemoveResultIDs(ids...)
	return _u
}

// RemoveResults removes "results" edges to Result entities.
func (_u *GameUpdateOne) RemoveResults(v ...*Result) *GameUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveResultIDs(ids...)
}

// Where appends a list predicates to the GameUpdate builder.
func (_u *GameUpdateOne) Where(ps ...predicate.Game) *GameUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *GameUpdateOne) Select(field string, fields ...string) *GameUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Game entity.
func (_u *GameUpdateOne) Save(ctx context.Context) (*Game, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *GameUpdateOne) SaveX(ctx context.Context) *Game {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *GameUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *GameUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

func (_u *GameUpdateOne) sqlSave(ctx context.Context) (_node *Game, err error) {
	_spec := sqlgraph.NewUpdateSpec(game.Table, game.Columns, sqlgraph.NewFieldSpec(game.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Game.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, game.FieldID)
		for _, f := range fields {
			if !game.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != game.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.TimeStamp(); ok {
		_spec.SetField(game.FieldTimeStamp, field.TypeTime, value)
	}
	if value, ok := _u.mutation.GetType(); ok {
		_spec.SetField(game.FieldType, field.TypeString, value)
	}
	if value, ok := _u.mutation.NbPlayer(); ok {
		_spec.SetField(game.FieldNbPlayer, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedNbPlayer(); ok {
		_spec.AddField(game.FieldNbPlayer, field.TypeInt, value)
	}
	if _u.mutation.ResultsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   game.ResultsTable,
			Columns: []string{game.ResultsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(result.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedResultsIDs(); len(nodes) > 0 && !_u.mutation.ResultsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   game.ResultsTable,
			Columns: []string{game.ResultsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(result.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ResultsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   game.ResultsTable,
			Columns: []string{game.ResultsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(result.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Game{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{game.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
