// Code generated by ent, DO NOT EDIT.

package ent

import (
	"backend/ent/mailverif"
	"backend/ent/predicate"
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// MailVerifDelete is the builder for deleting a MailVerif entity.
type MailVerifDelete struct {
	config
	hooks    []Hook
	mutation *MailVerifMutation
}

// Where appends a list predicates to the MailVerifDelete builder.
func (_d *MailVerifDelete) Where(ps ...predicate.MailVerif) *MailVerifDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *MailVerifDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *MailVerifDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *MailVerifDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(mailverif.Table, sqlgraph.NewFieldSpec(mailverif.FieldID, field.TypeInt))
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// MailVerifDeleteOne is the builder for deleting a single MailVerif entity.
type MailVerifDeleteOne struct {
	_d *MailVerifDelete
}

// Where appends a list predicates to the MailVerifDelete builder.
func (_d *MailVerifDeleteOne) Where(ps ...predicate.MailVerif) *MailVerifDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *MailVerifDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{mailverif.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *MailVerifDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
