// Code generated by ent, DO NOT EDIT.

package ent

import (
	"backend/ent/mailverif"
	"backend/ent/user"
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
)

// MailVerif is the model entity for the MailVerif schema.
type MailVerif struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// UserID holds the value of the "user_id" field.
	UserID int `json:"user_id,omitempty"`
	// Token holds the value of the "token" field.
	Token string `json:"token,omitempty"`
	// ExpiringAt holds the value of the "expiring_at" field.
	ExpiringAt time.Time `json:"expiring_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the MailVerifQuery when eager-loading is set.
	Edges        MailVerifEdges `json:"edges"`
	selectValues sql.SelectValues
}

// MailVerifEdges holds the relations/edges for other nodes in the graph.
type MailVerifEdges struct {
	// User holds the value of the user edge.
	User *User `json:"user,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// UserOrErr returns the User value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e MailVerifEdges) UserOrErr() (*User, error) {
	if e.User != nil {
		return e.User, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: user.Label}
	}
	return nil, &NotLoadedError{edge: "user"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*MailVerif) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case mailverif.FieldID, mailverif.FieldUserID:
			values[i] = new(sql.NullInt64)
		case mailverif.FieldToken:
			values[i] = new(sql.NullString)
		case mailverif.FieldExpiringAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the MailVerif fields.
func (_m *MailVerif) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case mailverif.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int(value.Int64)
		case mailverif.FieldUserID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field user_id", values[i])
			} else if value.Valid {
				_m.UserID = int(value.Int64)
			}
		case mailverif.FieldToken:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field token", values[i])
			} else if value.Valid {
				_m.Token = value.String
			}
		case mailverif.FieldExpiringAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field expiring_at", values[i])
			} else if value.Valid {
				_m.ExpiringAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the MailVerif.
// This includes values selected through modifiers, order, etc.
func (_m *MailVerif) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryUser queries the "user" edge of the MailVerif entity.
func (_m *MailVerif) QueryUser() *UserQuery {
	return NewMailVerifClient(_m.config).QueryUser(_m)
}

// Update returns a builder for updating this MailVerif.
// Note that you need to call MailVerif.Unwrap() before calling this method if this MailVerif
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *MailVerif) Update() *MailVerifUpdateOne {
	return NewMailVerifClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the MailVerif entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *MailVerif) Unwrap() *MailVerif {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: MailVerif is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *MailVerif) String() string {
	var builder strings.Builder
	builder.WriteString("MailVerif(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("user_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.UserID))
	builder.WriteString(", ")
	builder.WriteString("token=")
	builder.WriteString(_m.Token)
	builder.WriteString(", ")
	builder.WriteString("expiring_at=")
	builder.WriteString(_m.ExpiringAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// MailVerifs is a parsable slice of MailVerif.
type MailVerifs []*MailVerif
