// Code generated by ent, DO NOT EDIT.

package ent

import (
	"backend/ent/mailverif"
	"backend/ent/predicate"
	"backend/ent/user"
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// MailVerifUpdate is the builder for updating MailVerif entities.
type MailVerifUpdate struct {
	config
	hooks    []Hook
	mutation *MailVerifMutation
}

// Where appends a list predicates to the MailVerifUpdate builder.
func (_u *MailVerifUpdate) Where(ps ...predicate.MailVerif) *MailVerifUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *MailVerifUpdate) SetUserID(v int) *MailVerifUpdate {
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *MailVerifUpdate) SetNillableUserID(v *int) *MailVerifUpdate {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// SetToken sets the "token" field.
func (_u *MailVerifUpdate) SetToken(v string) *MailVerifUpdate {
	_u.mutation.SetToken(v)
	return _u
}

// SetNillableToken sets the "token" field if the given value is not nil.
func (_u *MailVerifUpdate) SetNillableToken(v *string) *MailVerifUpdate {
	if v != nil {
		_u.SetToken(*v)
	}
	return _u
}

// SetExpiringAt sets the "expiring_at" field.
func (_u *MailVerifUpdate) SetExpiringAt(v time.Time) *MailVerifUpdate {
	_u.mutation.SetExpiringAt(v)
	return _u
}

// SetNillableExpiringAt sets the "expiring_at" field if the given value is not nil.
func (_u *MailVerifUpdate) SetNillableExpiringAt(v *time.Time) *MailVerifUpdate {
	if v != nil {
		_u.SetExpiringAt(*v)
	}
	return _u
}

// SetUser sets the "user" edge to the User entity.
func (_u *MailVerifUpdate) SetUser(v *User) *MailVerifUpdate {
	return _u.SetUserID(v.ID)
}

// Mutation returns the MailVerifMutation object of the builder.
func (_u *MailVerifUpdate) Mutation() *MailVerifMutation {
	return _u.mutation
}

// ClearUser clears the "user" edge to the User entity.
func (_u *MailVerifUpdate) ClearUser() *MailVerifUpdate {
	_u.mutation.ClearUser()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *MailVerifUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *MailVerifUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *MailVerifUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *MailVerifUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *MailVerifUpdate) check() error {
	if v, ok := _u.mutation.UserID(); ok {
		if err := mailverif.UserIDValidator(v); err != nil {
			return &ValidationError{Name: "user_id", err: fmt.Errorf(`ent: validator failed for field "MailVerif.user_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Token(); ok {
		if err := mailverif.TokenValidator(v); err != nil {
			return &ValidationError{Name: "token", err: fmt.Errorf(`ent: validator failed for field "MailVerif.token": %w`, err)}
		}
	}
	if _u.mutation.UserCleared() && len(_u.mutation.UserIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "MailVerif.user"`)
	}
	return nil
}

func (_u *MailVerifUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(mailverif.Table, mailverif.Columns, sqlgraph.NewFieldSpec(mailverif.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Token(); ok {
		_spec.SetField(mailverif.FieldToken, field.TypeString, value)
	}
	if value, ok := _u.mutation.ExpiringAt(); ok {
		_spec.SetField(mailverif.FieldExpiringAt, field.TypeTime, value)
	}
	if _u.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: true,
			Table:   mailverif.UserTable,
			Columns: []string{mailverif.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: true,
			Table:   mailverif.UserTable,
			Columns: []string{mailverif.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{mailverif.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// MailVerifUpdateOne is the builder for updating a single MailVerif entity.
type MailVerifUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *MailVerifMutation
}

// SetUserID sets the "user_id" field.
func (_u *MailVerifUpdateOne) SetUserID(v int) *MailVerifUpdateOne {
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *MailVerifUpdateOne) SetNillableUserID(v *int) *MailVerifUpdateOne {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// SetToken sets the "token" field.
func (_u *MailVerifUpdateOne) SetToken(v string) *MailVerifUpdateOne {
	_u.mutation.SetToken(v)
	return _u
}

// SetNillableToken sets the "token" field if the given value is not nil.
func (_u *MailVerifUpdateOne) SetNillableToken(v *string) *MailVerifUpdateOne {
	if v != nil {
		_u.SetToken(*v)
	}
	return _u
}

// SetExpiringAt sets the "expiring_at" field.
func (_u *MailVerifUpdateOne) SetExpiringAt(v time.Time) *MailVerifUpdateOne {
	_u.mutation.SetExpiringAt(v)
	return _u
}

// SetNillableExpiringAt sets the "expiring_at" field if the given value is not nil.
func (_u *MailVerifUpdateOne) SetNillableExpiringAt(v *time.Time) *MailVerifUpdateOne {
	if v != nil {
		_u.SetExpiringAt(*v)
	}
	return _u
}

// SetUser sets the "user" edge to the User entity.
func (_u *MailVerifUpdateOne) SetUser(v *User) *MailVerifUpdateOne {
	return _u.SetUserID(v.ID)
}

// Mutation returns the MailVerifMutation object of the builder.
func (_u *MailVerifUpdateOne) Mutation() *MailVerifMutation {
	return _u.mutation
}

// ClearUser clears the "user" edge to the User entity.
func (_u *MailVerifUpdateOne) ClearUser() *MailVerifUpdateOne {
	_u.mutation.ClearUser()
	return _u
}

// Where appends a list predicates to the MailVerifUpdate builder.
func (_u *MailVerifUpdateOne) Where(ps ...predicate.MailVerif) *MailVerifUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *MailVerifUpdateOne) Select(field string, fields ...string) *MailVerifUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated MailVerif entity.
func (_u *MailVerifUpdateOne) Save(ctx context.Context) (*MailVerif, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *MailVerifUpdateOne) SaveX(ctx context.Context) *MailVerif {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *MailVerifUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *MailVerifUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *MailVerifUpdateOne) check() error {
	if v, ok := _u.mutation.UserID(); ok {
		if err := mailverif.UserIDValidator(v); err != nil {
			return &ValidationError{Name: "user_id", err: fmt.Errorf(`ent: validator failed for field "MailVerif.user_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Token(); ok {
		if err := mailverif.TokenValidator(v); err != nil {
			return &ValidationError{Name: "token", err: fmt.Errorf(`ent: validator failed for field "MailVerif.token": %w`, err)}
		}
	}
	if _u.mutation.UserCleared() && len(_u.mutation.UserIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "MailVerif.user"`)
	}
	return nil
}

func (_u *MailVerifUpdateOne) sqlSave(ctx context.Context) (_node *MailVerif, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(mailverif.Table, mailverif.Columns, sqlgraph.NewFieldSpec(mailverif.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "MailVerif.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, mailverif.FieldID)
		for _, f := range fields {
			if !mailverif.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != mailverif.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Token(); ok {
		_spec.SetField(mailverif.FieldToken, field.TypeString, value)
	}
	if value, ok := _u.mutation.ExpiringAt(); ok {
		_spec.SetField(mailverif.FieldExpiringAt, field.TypeTime, value)
	}
	if _u.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: true,
			Table:   mailverif.UserTable,
			Columns: []string{mailverif.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: true,
			Table:   mailverif.UserTable,
			Columns: []string{mailverif.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &MailVerif{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{mailverif.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
