// Code generated by ent, DO NOT EDIT.

package ent

import (
	"backend/ent/mailverif"
	"backend/ent/user"
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// MailVerifCreate is the builder for creating a MailVerif entity.
type MailVerifCreate struct {
	config
	mutation *MailVerifMutation
	hooks    []Hook
}

// SetUserID sets the "user_id" field.
func (_c *MailVerifCreate) SetUserID(v int) *MailVerifCreate {
	_c.mutation.SetUserID(v)
	return _c
}

// SetToken sets the "token" field.
func (_c *MailVerifCreate) SetToken(v string) *MailVerifCreate {
	_c.mutation.SetToken(v)
	return _c
}

// SetExpiringAt sets the "expiring_at" field.
func (_c *MailVerifCreate) SetExpiringAt(v time.Time) *MailVerifCreate {
	_c.mutation.SetExpiringAt(v)
	return _c
}

// SetNillableExpiringAt sets the "expiring_at" field if the given value is not nil.
func (_c *MailVerifCreate) SetNillableExpiringAt(v *time.Time) *MailVerifCreate {
	if v != nil {
		_c.SetExpiringAt(*v)
	}
	return _c
}

// SetUser sets the "user" edge to the User entity.
func (_c *MailVerifCreate) SetUser(v *User) *MailVerifCreate {
	return _c.SetUserID(v.ID)
}

// Mutation returns the MailVerifMutation object of the builder.
func (_c *MailVerifCreate) Mutation() *MailVerifMutation {
	return _c.mutation
}

// Save creates the MailVerif in the database.
func (_c *MailVerifCreate) Save(ctx context.Context) (*MailVerif, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *MailVerifCreate) SaveX(ctx context.Context) *MailVerif {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *MailVerifCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *MailVerifCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *MailVerifCreate) defaults() {
	if _, ok := _c.mutation.ExpiringAt(); !ok {
		v := mailverif.DefaultExpiringAt()
		_c.mutation.SetExpiringAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *MailVerifCreate) check() error {
	if _, ok := _c.mutation.UserID(); !ok {
		return &ValidationError{Name: "user_id", err: errors.New(`ent: missing required field "MailVerif.user_id"`)}
	}
	if v, ok := _c.mutation.UserID(); ok {
		if err := mailverif.UserIDValidator(v); err != nil {
			return &ValidationError{Name: "user_id", err: fmt.Errorf(`ent: validator failed for field "MailVerif.user_id": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Token(); !ok {
		return &ValidationError{Name: "token", err: errors.New(`ent: missing required field "MailVerif.token"`)}
	}
	if v, ok := _c.mutation.Token(); ok {
		if err := mailverif.TokenValidator(v); err != nil {
			return &ValidationError{Name: "token", err: fmt.Errorf(`ent: validator failed for field "MailVerif.token": %w`, err)}
		}
	}
	if _, ok := _c.mutation.ExpiringAt(); !ok {
		return &ValidationError{Name: "expiring_at", err: errors.New(`ent: missing required field "MailVerif.expiring_at"`)}
	}
	if len(_c.mutation.UserIDs()) == 0 {
		return &ValidationError{Name: "user", err: errors.New(`ent: missing required edge "MailVerif.user"`)}
	}
	return nil
}

func (_c *MailVerifCreate) sqlSave(ctx context.Context) (*MailVerif, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *MailVerifCreate) createSpec() (*MailVerif, *sqlgraph.CreateSpec) {
	var (
		_node = &MailVerif{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(mailverif.Table, sqlgraph.NewFieldSpec(mailverif.FieldID, field.TypeInt))
	)
	if value, ok := _c.mutation.Token(); ok {
		_spec.SetField(mailverif.FieldToken, field.TypeString, value)
		_node.Token = value
	}
	if value, ok := _c.mutation.ExpiringAt(); ok {
		_spec.SetField(mailverif.FieldExpiringAt, field.TypeTime, value)
		_node.ExpiringAt = value
	}
	if nodes := _c.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: true,
			Table:   mailverif.UserTable,
			Columns: []string{mailverif.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.UserID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// MailVerifCreateBulk is the builder for creating many MailVerif entities in bulk.
type MailVerifCreateBulk struct {
	config
	err      error
	builders []*MailVerifCreate
}

// Save creates the MailVerif entities in the database.
func (_c *MailVerifCreateBulk) Save(ctx context.Context) ([]*MailVerif, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*MailVerif, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*MailVerifMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *MailVerifCreateBulk) SaveX(ctx context.Context) []*MailVerif {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *MailVerifCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *MailVerifCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
