// Code generated by ent, DO NOT EDIT.

package ent

import (
	"backend/ent/conversation"
	"backend/ent/friendship"
	"backend/ent/mailverif"
	"backend/ent/message"
	"backend/ent/schema"
	"backend/ent/user"
	"time"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	conversationFields := schema.Conversation{}.Fields()
	_ = conversationFields
	// conversationDescCreatedAt is the schema descriptor for created_at field.
	conversationDescCreatedAt := conversationFields[0].Descriptor()
	// conversation.DefaultCreatedAt holds the default value on creation for the created_at field.
	conversation.DefaultCreatedAt = conversationDescCreatedAt.Default.(func() time.Time)
	friendshipFields := schema.Friendship{}.Fields()
	_ = friendshipFields
	// friendshipDescCreatedAt is the schema descriptor for created_at field.
	friendshipDescCreatedAt := friendshipFields[0].Descriptor()
	// friendship.DefaultCreatedAt holds the default value on creation for the created_at field.
	friendship.DefaultCreatedAt = friendshipDescCreatedAt.Default.(func() time.Time)
	// friendshipDescStatus is the schema descriptor for status field.
	friendshipDescStatus := friendshipFields[1].Descriptor()
	// friendship.DefaultStatus holds the default value on creation for the status field.
	friendship.DefaultStatus = friendshipDescStatus.Default.(string)
	mailverifFields := schema.MailVerif{}.Fields()
	_ = mailverifFields
	// mailverifDescUserID is the schema descriptor for user_id field.
	mailverifDescUserID := mailverifFields[0].Descriptor()
	// mailverif.UserIDValidator is a validator for the "user_id" field. It is called by the builders before save.
	mailverif.UserIDValidator = mailverifDescUserID.Validators[0].(func(int) error)
	// mailverifDescToken is the schema descriptor for token field.
	mailverifDescToken := mailverifFields[1].Descriptor()
	// mailverif.TokenValidator is a validator for the "token" field. It is called by the builders before save.
	mailverif.TokenValidator = mailverifDescToken.Validators[0].(func(string) error)
	// mailverifDescExpiringAt is the schema descriptor for expiring_at field.
	mailverifDescExpiringAt := mailverifFields[2].Descriptor()
	// mailverif.DefaultExpiringAt holds the default value on creation for the expiring_at field.
	mailverif.DefaultExpiringAt = mailverifDescExpiringAt.Default.(func() time.Time)
	messageFields := schema.Message{}.Fields()
	_ = messageFields
	// messageDescContent is the schema descriptor for content field.
	messageDescContent := messageFields[0].Descriptor()
	// message.ContentValidator is a validator for the "content" field. It is called by the builders before save.
	message.ContentValidator = messageDescContent.Validators[0].(func(string) error)
	// messageDescCreatedAt is the schema descriptor for created_at field.
	messageDescCreatedAt := messageFields[1].Descriptor()
	// message.DefaultCreatedAt holds the default value on creation for the created_at field.
	message.DefaultCreatedAt = messageDescCreatedAt.Default.(func() time.Time)
	userFields := schema.User{}.Fields()
	_ = userFields
	// userDescUsername is the schema descriptor for username field.
	userDescUsername := userFields[0].Descriptor()
	// user.UsernameValidator is a validator for the "username" field. It is called by the builders before save.
	user.UsernameValidator = userDescUsername.Validators[0].(func(string) error)
	// userDescAge is the schema descriptor for age field.
	userDescAge := userFields[1].Descriptor()
	// user.AgeValidator is a validator for the "age" field. It is called by the builders before save.
	user.AgeValidator = func() func(int) error {
		validators := userDescAge.Validators
		fns := [...]func(int) error{
			validators[0].(func(int) error),
			validators[1].(func(int) error),
		}
		return func(age int) error {
			for _, fn := range fns {
				if err := fn(age); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// userDescEmail is the schema descriptor for email field.
	userDescEmail := userFields[2].Descriptor()
	// user.EmailValidator is a validator for the "email" field. It is called by the builders before save.
	user.EmailValidator = userDescEmail.Validators[0].(func(string) error)
	// userDescCreatedAt is the schema descriptor for created_at field.
	userDescCreatedAt := userFields[3].Descriptor()
	// user.DefaultCreatedAt holds the default value on creation for the created_at field.
	user.DefaultCreatedAt = userDescCreatedAt.Default.(func() time.Time)
	// userDescVerifiedEmail is the schema descriptor for verified_email field.
	userDescVerifiedEmail := userFields[6].Descriptor()
	// user.DefaultVerifiedEmail holds the default value on creation for the verified_email field.
	user.DefaultVerifiedEmail = userDescVerifiedEmail.Default.(bool)
	// userDescPpPath is the schema descriptor for pp_path field.
	userDescPpPath := userFields[7].Descriptor()
	// user.DefaultPpPath holds the default value on creation for the pp_path field.
	user.DefaultPpPath = userDescPpPath.Default.(string)
}
