// Code generated by ent, DO NOT EDIT.

package ent

import (
	"backend/ent/mailverif"
	"backend/ent/user"
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
)

// User is the model entity for the User schema.
type User struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// Username holds the value of the "username" field.
	Username string `json:"username,omitempty"`
	// Age holds the value of the "age" field.
	Age int `json:"age,omitempty"`
	// Email holds the value of the "email" field.
	Email string `json:"email,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// Salt holds the value of the "salt" field.
	Salt string `json:"salt,omitempty"`
	// Hash holds the value of the "hash" field.
	Hash string `json:"hash,omitempty"`
	// VerifiedEmail holds the value of the "verified_email" field.
	VerifiedEmail bool `json:"verified_email,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the UserQuery when eager-loading is set.
	Edges        UserEdges `json:"edges"`
	selectValues sql.SelectValues
}

// UserEdges holds the relations/edges for other nodes in the graph.
type UserEdges struct {
	// MailVerif holds the value of the mail_verif edge.
	MailVerif *MailVerif `json:"mail_verif,omitempty"`
	// Friendships holds the value of the friendships edge.
	Friendships []*Friendship `json:"friendships,omitempty"`
	// FriendOf holds the value of the friend_of edge.
	FriendOf []*Friendship `json:"friend_of,omitempty"`
	// SendMessages holds the value of the send_messages edge.
	SendMessages []*Message `json:"send_messages,omitempty"`
	// Conversations holds the value of the conversations edge.
	Conversations []*Conversation `json:"conversations,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [5]bool
}

// MailVerifOrErr returns the MailVerif value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e UserEdges) MailVerifOrErr() (*MailVerif, error) {
	if e.MailVerif != nil {
		return e.MailVerif, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: mailverif.Label}
	}
	return nil, &NotLoadedError{edge: "mail_verif"}
}

// FriendshipsOrErr returns the Friendships value or an error if the edge
// was not loaded in eager-loading.
func (e UserEdges) FriendshipsOrErr() ([]*Friendship, error) {
	if e.loadedTypes[1] {
		return e.Friendships, nil
	}
	return nil, &NotLoadedError{edge: "friendships"}
}

// FriendOfOrErr returns the FriendOf value or an error if the edge
// was not loaded in eager-loading.
func (e UserEdges) FriendOfOrErr() ([]*Friendship, error) {
	if e.loadedTypes[2] {
		return e.FriendOf, nil
	}
	return nil, &NotLoadedError{edge: "friend_of"}
}

// SendMessagesOrErr returns the SendMessages value or an error if the edge
// was not loaded in eager-loading.
func (e UserEdges) SendMessagesOrErr() ([]*Message, error) {
	if e.loadedTypes[3] {
		return e.SendMessages, nil
	}
	return nil, &NotLoadedError{edge: "send_messages"}
}

// ConversationsOrErr returns the Conversations value or an error if the edge
// was not loaded in eager-loading.
func (e UserEdges) ConversationsOrErr() ([]*Conversation, error) {
	if e.loadedTypes[4] {
		return e.Conversations, nil
	}
	return nil, &NotLoadedError{edge: "conversations"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*User) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case user.FieldVerifiedEmail:
			values[i] = new(sql.NullBool)
		case user.FieldID, user.FieldAge:
			values[i] = new(sql.NullInt64)
		case user.FieldUsername, user.FieldEmail, user.FieldSalt, user.FieldHash:
			values[i] = new(sql.NullString)
		case user.FieldCreatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the User fields.
func (_m *User) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case user.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int(value.Int64)
		case user.FieldUsername:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field username", values[i])
			} else if value.Valid {
				_m.Username = value.String
			}
		case user.FieldAge:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field age", values[i])
			} else if value.Valid {
				_m.Age = int(value.Int64)
			}
		case user.FieldEmail:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field email", values[i])
			} else if value.Valid {
				_m.Email = value.String
			}
		case user.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case user.FieldSalt:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field salt", values[i])
			} else if value.Valid {
				_m.Salt = value.String
			}
		case user.FieldHash:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field hash", values[i])
			} else if value.Valid {
				_m.Hash = value.String
			}
		case user.FieldVerifiedEmail:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field verified_email", values[i])
			} else if value.Valid {
				_m.VerifiedEmail = value.Bool
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the User.
// This includes values selected through modifiers, order, etc.
func (_m *User) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryMailVerif queries the "mail_verif" edge of the User entity.
func (_m *User) QueryMailVerif() *MailVerifQuery {
	return NewUserClient(_m.config).QueryMailVerif(_m)
}

// QueryFriendships queries the "friendships" edge of the User entity.
func (_m *User) QueryFriendships() *FriendshipQuery {
	return NewUserClient(_m.config).QueryFriendships(_m)
}

// QueryFriendOf queries the "friend_of" edge of the User entity.
func (_m *User) QueryFriendOf() *FriendshipQuery {
	return NewUserClient(_m.config).QueryFriendOf(_m)
}

// QuerySendMessages queries the "send_messages" edge of the User entity.
func (_m *User) QuerySendMessages() *MessageQuery {
	return NewUserClient(_m.config).QuerySendMessages(_m)
}

// QueryConversations queries the "conversations" edge of the User entity.
func (_m *User) QueryConversations() *ConversationQuery {
	return NewUserClient(_m.config).QueryConversations(_m)
}

// Update returns a builder for updating this User.
// Note that you need to call User.Unwrap() before calling this method if this User
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *User) Update() *UserUpdateOne {
	return NewUserClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the User entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *User) Unwrap() *User {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: User is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *User) String() string {
	var builder strings.Builder
	builder.WriteString("User(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("username=")
	builder.WriteString(_m.Username)
	builder.WriteString(", ")
	builder.WriteString("age=")
	builder.WriteString(fmt.Sprintf("%v", _m.Age))
	builder.WriteString(", ")
	builder.WriteString("email=")
	builder.WriteString(_m.Email)
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("salt=")
	builder.WriteString(_m.Salt)
	builder.WriteString(", ")
	builder.WriteString("hash=")
	builder.WriteString(_m.Hash)
	builder.WriteString(", ")
	builder.WriteString("verified_email=")
	builder.WriteString(fmt.Sprintf("%v", _m.VerifiedEmail))
	builder.WriteByte(')')
	return builder.String()
}

// Users is a parsable slice of User.
type Users []*User
