// Code generated by ent, DO NOT EDIT.

package mailverif

import (
	"backend/ent/predicate"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.MailVerif {
	return predicate.MailVerif(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.MailVerif {
	return predicate.MailVerif(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.MailVerif {
	return predicate.MailVerif(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.MailVerif {
	return predicate.MailVerif(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.MailVerif {
	return predicate.MailVerif(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.MailVerif {
	return predicate.MailVerif(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.MailVerif {
	return predicate.MailVerif(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.MailVerif {
	return predicate.MailVerif(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.MailVerif {
	return predicate.MailVerif(sql.FieldLTE(FieldID, id))
}

// UserID applies equality check predicate on the "user_id" field. It's identical to UserIDEQ.
func UserID(v int) predicate.MailVerif {
	return predicate.MailVerif(sql.FieldEQ(FieldUserID, v))
}

// Token applies equality check predicate on the "token" field. It's identical to TokenEQ.
func Token(v string) predicate.MailVerif {
	return predicate.MailVerif(sql.FieldEQ(FieldToken, v))
}

// ExpiringAt applies equality check predicate on the "expiring_at" field. It's identical to ExpiringAtEQ.
func ExpiringAt(v time.Time) predicate.MailVerif {
	return predicate.MailVerif(sql.FieldEQ(FieldExpiringAt, v))
}

// UserIDEQ applies the EQ predicate on the "user_id" field.
func UserIDEQ(v int) predicate.MailVerif {
	return predicate.MailVerif(sql.FieldEQ(FieldUserID, v))
}

// UserIDNEQ applies the NEQ predicate on the "user_id" field.
func UserIDNEQ(v int) predicate.MailVerif {
	return predicate.MailVerif(sql.FieldNEQ(FieldUserID, v))
}

// UserIDIn applies the In predicate on the "user_id" field.
func UserIDIn(vs ...int) predicate.MailVerif {
	return predicate.MailVerif(sql.FieldIn(FieldUserID, vs...))
}

// UserIDNotIn applies the NotIn predicate on the "user_id" field.
func UserIDNotIn(vs ...int) predicate.MailVerif {
	return predicate.MailVerif(sql.FieldNotIn(FieldUserID, vs...))
}

// TokenEQ applies the EQ predicate on the "token" field.
func TokenEQ(v string) predicate.MailVerif {
	return predicate.MailVerif(sql.FieldEQ(FieldToken, v))
}

// TokenNEQ applies the NEQ predicate on the "token" field.
func TokenNEQ(v string) predicate.MailVerif {
	return predicate.MailVerif(sql.FieldNEQ(FieldToken, v))
}

// TokenIn applies the In predicate on the "token" field.
func TokenIn(vs ...string) predicate.MailVerif {
	return predicate.MailVerif(sql.FieldIn(FieldToken, vs...))
}

// TokenNotIn applies the NotIn predicate on the "token" field.
func TokenNotIn(vs ...string) predicate.MailVerif {
	return predicate.MailVerif(sql.FieldNotIn(FieldToken, vs...))
}

// TokenGT applies the GT predicate on the "token" field.
func TokenGT(v string) predicate.MailVerif {
	return predicate.MailVerif(sql.FieldGT(FieldToken, v))
}

// TokenGTE applies the GTE predicate on the "token" field.
func TokenGTE(v string) predicate.MailVerif {
	return predicate.MailVerif(sql.FieldGTE(FieldToken, v))
}

// TokenLT applies the LT predicate on the "token" field.
func TokenLT(v string) predicate.MailVerif {
	return predicate.MailVerif(sql.FieldLT(FieldToken, v))
}

// TokenLTE applies the LTE predicate on the "token" field.
func TokenLTE(v string) predicate.MailVerif {
	return predicate.MailVerif(sql.FieldLTE(FieldToken, v))
}

// TokenContains applies the Contains predicate on the "token" field.
func TokenContains(v string) predicate.MailVerif {
	return predicate.MailVerif(sql.FieldContains(FieldToken, v))
}

// TokenHasPrefix applies the HasPrefix predicate on the "token" field.
func TokenHasPrefix(v string) predicate.MailVerif {
	return predicate.MailVerif(sql.FieldHasPrefix(FieldToken, v))
}

// TokenHasSuffix applies the HasSuffix predicate on the "token" field.
func TokenHasSuffix(v string) predicate.MailVerif {
	return predicate.MailVerif(sql.FieldHasSuffix(FieldToken, v))
}

// TokenEqualFold applies the EqualFold predicate on the "token" field.
func TokenEqualFold(v string) predicate.MailVerif {
	return predicate.MailVerif(sql.FieldEqualFold(FieldToken, v))
}

// TokenContainsFold applies the ContainsFold predicate on the "token" field.
func TokenContainsFold(v string) predicate.MailVerif {
	return predicate.MailVerif(sql.FieldContainsFold(FieldToken, v))
}

// ExpiringAtEQ applies the EQ predicate on the "expiring_at" field.
func ExpiringAtEQ(v time.Time) predicate.MailVerif {
	return predicate.MailVerif(sql.FieldEQ(FieldExpiringAt, v))
}

// ExpiringAtNEQ applies the NEQ predicate on the "expiring_at" field.
func ExpiringAtNEQ(v time.Time) predicate.MailVerif {
	return predicate.MailVerif(sql.FieldNEQ(FieldExpiringAt, v))
}

// ExpiringAtIn applies the In predicate on the "expiring_at" field.
func ExpiringAtIn(vs ...time.Time) predicate.MailVerif {
	return predicate.MailVerif(sql.FieldIn(FieldExpiringAt, vs...))
}

// ExpiringAtNotIn applies the NotIn predicate on the "expiring_at" field.
func ExpiringAtNotIn(vs ...time.Time) predicate.MailVerif {
	return predicate.MailVerif(sql.FieldNotIn(FieldExpiringAt, vs...))
}

// ExpiringAtGT applies the GT predicate on the "expiring_at" field.
func ExpiringAtGT(v time.Time) predicate.MailVerif {
	return predicate.MailVerif(sql.FieldGT(FieldExpiringAt, v))
}

// ExpiringAtGTE applies the GTE predicate on the "expiring_at" field.
func ExpiringAtGTE(v time.Time) predicate.MailVerif {
	return predicate.MailVerif(sql.FieldGTE(FieldExpiringAt, v))
}

// ExpiringAtLT applies the LT predicate on the "expiring_at" field.
func ExpiringAtLT(v time.Time) predicate.MailVerif {
	return predicate.MailVerif(sql.FieldLT(FieldExpiringAt, v))
}

// ExpiringAtLTE applies the LTE predicate on the "expiring_at" field.
func ExpiringAtLTE(v time.Time) predicate.MailVerif {
	return predicate.MailVerif(sql.FieldLTE(FieldExpiringAt, v))
}

// HasUser applies the HasEdge predicate on the "user" edge.
func HasUser() predicate.MailVerif {
	return predicate.MailVerif(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2O, true, UserTable, UserColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasUserWith applies the HasEdge predicate on the "user" edge with a given conditions (other predicates).
func HasUserWith(preds ...predicate.User) predicate.MailVerif {
	return predicate.MailVerif(func(s *sql.Selector) {
		step := newUserStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.MailVerif) predicate.MailVerif {
	return predicate.MailVerif(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.MailVerif) predicate.MailVerif {
	return predicate.MailVerif(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.MailVerif) predicate.MailVerif {
	return predicate.MailVerif(sql.NotPredicates(p))
}
