// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// ConversationsColumns holds the columns for the "conversations" table.
	ConversationsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "created_at", Type: field.TypeTime},
	}
	// ConversationsTable holds the schema information for the "conversations" table.
	ConversationsTable = &schema.Table{
		Name:       "conversations",
		Columns:    ConversationsColumns,
		PrimaryKey: []*schema.Column{ConversationsColumns[0]},
	}
	// FriendshipsColumns holds the columns for the "friendships" table.
	FriendshipsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "status", Type: field.TypeString, Default: "pending"},
		{Name: "user_friendships", Type: field.TypeInt},
		{Name: "user_friend_of", Type: field.TypeInt},
	}
	// FriendshipsTable holds the schema information for the "friendships" table.
	FriendshipsTable = &schema.Table{
		Name:       "friendships",
		Columns:    FriendshipsColumns,
		PrimaryKey: []*schema.Column{FriendshipsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "friendships_users_friendships",
				Columns:    []*schema.Column{FriendshipsColumns[3]},
				RefColumns: []*schema.Column{UsersColumns[0]},
				OnDelete:   schema.Cascade,
			},
			{
				Symbol:     "friendships_users_friend_of",
				Columns:    []*schema.Column{FriendshipsColumns[4]},
				RefColumns: []*schema.Column{UsersColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
		Indexes: []*schema.Index{
			{
				Name:    "friendship_user_friendships_user_friend_of",
				Unique:  true,
				Columns: []*schema.Column{FriendshipsColumns[3], FriendshipsColumns[4]},
			},
		},
	}
	// MailVerifsColumns holds the columns for the "mail_verifs" table.
	MailVerifsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "token", Type: field.TypeString},
		{Name: "expiring_at", Type: field.TypeTime},
		{Name: "user_id", Type: field.TypeInt, Unique: true},
	}
	// MailVerifsTable holds the schema information for the "mail_verifs" table.
	MailVerifsTable = &schema.Table{
		Name:       "mail_verifs",
		Columns:    MailVerifsColumns,
		PrimaryKey: []*schema.Column{MailVerifsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "mail_verifs_users_mail_verif",
				Columns:    []*schema.Column{MailVerifsColumns[3]},
				RefColumns: []*schema.Column{UsersColumns[0]},
				OnDelete:   schema.Cascade,
			},
		},
	}
	// MessagesColumns holds the columns for the "messages" table.
	MessagesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "content", Type: field.TypeString},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "conversation_messages", Type: field.TypeInt},
		{Name: "user_send_messages", Type: field.TypeInt},
	}
	// MessagesTable holds the schema information for the "messages" table.
	MessagesTable = &schema.Table{
		Name:       "messages",
		Columns:    MessagesColumns,
		PrimaryKey: []*schema.Column{MessagesColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "messages_conversations_messages",
				Columns:    []*schema.Column{MessagesColumns[3]},
				RefColumns: []*schema.Column{ConversationsColumns[0]},
				OnDelete:   schema.NoAction,
			},
			{
				Symbol:     "messages_users_send_messages",
				Columns:    []*schema.Column{MessagesColumns[4]},
				RefColumns: []*schema.Column{UsersColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
		Indexes: []*schema.Index{
			{
				Name:    "message_created_at",
				Unique:  false,
				Columns: []*schema.Column{MessagesColumns[2]},
			},
		},
	}
	// UsersColumns holds the columns for the "users" table.
	UsersColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "username", Type: field.TypeString, Unique: true},
		{Name: "age", Type: field.TypeInt},
		{Name: "email", Type: field.TypeString, Unique: true, Size: 320},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "salt", Type: field.TypeString},
		{Name: "hash", Type: field.TypeString},
		{Name: "verified_email", Type: field.TypeBool, Default: false},
		{Name: "pp_path", Type: field.TypeString, Default: ""},
		{Name: "skin_color", Type: field.TypeString, Default: "#03fc6f"},
		{Name: "face_color", Type: field.TypeString, Default: "#eeeeee"},
	}
	// UsersTable holds the schema information for the "users" table.
	UsersTable = &schema.Table{
		Name:       "users",
		Columns:    UsersColumns,
		PrimaryKey: []*schema.Column{UsersColumns[0]},
	}
	// UserConversationsColumns holds the columns for the "user_conversations" table.
	UserConversationsColumns = []*schema.Column{
		{Name: "user_id", Type: field.TypeInt},
		{Name: "conversation_id", Type: field.TypeInt},
	}
	// UserConversationsTable holds the schema information for the "user_conversations" table.
	UserConversationsTable = &schema.Table{
		Name:       "user_conversations",
		Columns:    UserConversationsColumns,
		PrimaryKey: []*schema.Column{UserConversationsColumns[0], UserConversationsColumns[1]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "user_conversations_user_id",
				Columns:    []*schema.Column{UserConversationsColumns[0]},
				RefColumns: []*schema.Column{UsersColumns[0]},
				OnDelete:   schema.Cascade,
			},
			{
				Symbol:     "user_conversations_conversation_id",
				Columns:    []*schema.Column{UserConversationsColumns[1]},
				RefColumns: []*schema.Column{ConversationsColumns[0]},
				OnDelete:   schema.Cascade,
			},
		},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		ConversationsTable,
		FriendshipsTable,
		MailVerifsTable,
		MessagesTable,
		UsersTable,
		UserConversationsTable,
	}
)

func init() {
	FriendshipsTable.ForeignKeys[0].RefTable = UsersTable
	FriendshipsTable.ForeignKeys[1].RefTable = UsersTable
	MailVerifsTable.ForeignKeys[0].RefTable = UsersTable
	MessagesTable.ForeignKeys[0].RefTable = ConversationsTable
	MessagesTable.ForeignKeys[1].RefTable = UsersTable
	UserConversationsTable.ForeignKeys[0].RefTable = UsersTable
	UserConversationsTable.ForeignKeys[1].RefTable = ConversationsTable
}
