// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// FriendshipsColumns holds the columns for the "friendships" table.
	FriendshipsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "status", Type: field.TypeString, Default: "pending"},
		{Name: "user_friendships", Type: field.TypeInt},
		{Name: "user_friend_of", Type: field.TypeInt},
	}
	// FriendshipsTable holds the schema information for the "friendships" table.
	FriendshipsTable = &schema.Table{
		Name:       "friendships",
		Columns:    FriendshipsColumns,
		PrimaryKey: []*schema.Column{FriendshipsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "friendships_users_friendships",
				Columns:    []*schema.Column{FriendshipsColumns[3]},
				RefColumns: []*schema.Column{UsersColumns[0]},
				OnDelete:   schema.NoAction,
			},
			{
				Symbol:     "friendships_users_friend_of",
				Columns:    []*schema.Column{FriendshipsColumns[4]},
				RefColumns: []*schema.Column{UsersColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
		Indexes: []*schema.Index{
			{
				Name:    "friendship_user_friendships_user_friend_of",
				Unique:  true,
				Columns: []*schema.Column{FriendshipsColumns[3], FriendshipsColumns[4]},
			},
		},
	}
	// MailVerifsColumns holds the columns for the "mail_verifs" table.
	MailVerifsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "token", Type: field.TypeString},
		{Name: "expiring_at", Type: field.TypeTime},
		{Name: "user_id", Type: field.TypeInt, Unique: true},
	}
	// MailVerifsTable holds the schema information for the "mail_verifs" table.
	MailVerifsTable = &schema.Table{
		Name:       "mail_verifs",
		Columns:    MailVerifsColumns,
		PrimaryKey: []*schema.Column{MailVerifsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "mail_verifs_users_mail_verif",
				Columns:    []*schema.Column{MailVerifsColumns[3]},
				RefColumns: []*schema.Column{UsersColumns[0]},
				OnDelete:   schema.Cascade,
			},
		},
	}
	// UsersColumns holds the columns for the "users" table.
	UsersColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "username", Type: field.TypeString, Unique: true},
		{Name: "age", Type: field.TypeInt},
		{Name: "email", Type: field.TypeString, Unique: true, Size: 320},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "salt", Type: field.TypeString},
		{Name: "hash", Type: field.TypeString},
		{Name: "verified_email", Type: field.TypeBool, Default: false},
	}
	// UsersTable holds the schema information for the "users" table.
	UsersTable = &schema.Table{
		Name:       "users",
		Columns:    UsersColumns,
		PrimaryKey: []*schema.Column{UsersColumns[0]},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		FriendshipsTable,
		MailVerifsTable,
		UsersTable,
	}
)

func init() {
	FriendshipsTable.ForeignKeys[0].RefTable = UsersTable
	FriendshipsTable.ForeignKeys[1].RefTable = UsersTable
	MailVerifsTable.ForeignKeys[0].RefTable = UsersTable
}
