// Code generated by ent, DO NOT EDIT.

package game

import (
	"backend/ent/predicate"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.Game {
	return predicate.Game(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.Game {
	return predicate.Game(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.Game {
	return predicate.Game(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.Game {
	return predicate.Game(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.Game {
	return predicate.Game(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.Game {
	return predicate.Game(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.Game {
	return predicate.Game(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.Game {
	return predicate.Game(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.Game {
	return predicate.Game(sql.FieldLTE(FieldID, id))
}

// TimeStamp applies equality check predicate on the "time_stamp" field. It's identical to TimeStampEQ.
func TimeStamp(v time.Time) predicate.Game {
	return predicate.Game(sql.FieldEQ(FieldTimeStamp, v))
}

// Type applies equality check predicate on the "type" field. It's identical to TypeEQ.
func Type(v string) predicate.Game {
	return predicate.Game(sql.FieldEQ(FieldType, v))
}

// NbPlayer applies equality check predicate on the "nb_player" field. It's identical to NbPlayerEQ.
func NbPlayer(v int) predicate.Game {
	return predicate.Game(sql.FieldEQ(FieldNbPlayer, v))
}

// TimeStampEQ applies the EQ predicate on the "time_stamp" field.
func TimeStampEQ(v time.Time) predicate.Game {
	return predicate.Game(sql.FieldEQ(FieldTimeStamp, v))
}

// TimeStampNEQ applies the NEQ predicate on the "time_stamp" field.
func TimeStampNEQ(v time.Time) predicate.Game {
	return predicate.Game(sql.FieldNEQ(FieldTimeStamp, v))
}

// TimeStampIn applies the In predicate on the "time_stamp" field.
func TimeStampIn(vs ...time.Time) predicate.Game {
	return predicate.Game(sql.FieldIn(FieldTimeStamp, vs...))
}

// TimeStampNotIn applies the NotIn predicate on the "time_stamp" field.
func TimeStampNotIn(vs ...time.Time) predicate.Game {
	return predicate.Game(sql.FieldNotIn(FieldTimeStamp, vs...))
}

// TimeStampGT applies the GT predicate on the "time_stamp" field.
func TimeStampGT(v time.Time) predicate.Game {
	return predicate.Game(sql.FieldGT(FieldTimeStamp, v))
}

// TimeStampGTE applies the GTE predicate on the "time_stamp" field.
func TimeStampGTE(v time.Time) predicate.Game {
	return predicate.Game(sql.FieldGTE(FieldTimeStamp, v))
}

// TimeStampLT applies the LT predicate on the "time_stamp" field.
func TimeStampLT(v time.Time) predicate.Game {
	return predicate.Game(sql.FieldLT(FieldTimeStamp, v))
}

// TimeStampLTE applies the LTE predicate on the "time_stamp" field.
func TimeStampLTE(v time.Time) predicate.Game {
	return predicate.Game(sql.FieldLTE(FieldTimeStamp, v))
}

// TypeEQ applies the EQ predicate on the "type" field.
func TypeEQ(v string) predicate.Game {
	return predicate.Game(sql.FieldEQ(FieldType, v))
}

// TypeNEQ applies the NEQ predicate on the "type" field.
func TypeNEQ(v string) predicate.Game {
	return predicate.Game(sql.FieldNEQ(FieldType, v))
}

// TypeIn applies the In predicate on the "type" field.
func TypeIn(vs ...string) predicate.Game {
	return predicate.Game(sql.FieldIn(FieldType, vs...))
}

// TypeNotIn applies the NotIn predicate on the "type" field.
func TypeNotIn(vs ...string) predicate.Game {
	return predicate.Game(sql.FieldNotIn(FieldType, vs...))
}

// TypeGT applies the GT predicate on the "type" field.
func TypeGT(v string) predicate.Game {
	return predicate.Game(sql.FieldGT(FieldType, v))
}

// TypeGTE applies the GTE predicate on the "type" field.
func TypeGTE(v string) predicate.Game {
	return predicate.Game(sql.FieldGTE(FieldType, v))
}

// TypeLT applies the LT predicate on the "type" field.
func TypeLT(v string) predicate.Game {
	return predicate.Game(sql.FieldLT(FieldType, v))
}

// TypeLTE applies the LTE predicate on the "type" field.
func TypeLTE(v string) predicate.Game {
	return predicate.Game(sql.FieldLTE(FieldType, v))
}

// TypeContains applies the Contains predicate on the "type" field.
func TypeContains(v string) predicate.Game {
	return predicate.Game(sql.FieldContains(FieldType, v))
}

// TypeHasPrefix applies the HasPrefix predicate on the "type" field.
func TypeHasPrefix(v string) predicate.Game {
	return predicate.Game(sql.FieldHasPrefix(FieldType, v))
}

// TypeHasSuffix applies the HasSuffix predicate on the "type" field.
func TypeHasSuffix(v string) predicate.Game {
	return predicate.Game(sql.FieldHasSuffix(FieldType, v))
}

// TypeEqualFold applies the EqualFold predicate on the "type" field.
func TypeEqualFold(v string) predicate.Game {
	return predicate.Game(sql.FieldEqualFold(FieldType, v))
}

// TypeContainsFold applies the ContainsFold predicate on the "type" field.
func TypeContainsFold(v string) predicate.Game {
	return predicate.Game(sql.FieldContainsFold(FieldType, v))
}

// NbPlayerEQ applies the EQ predicate on the "nb_player" field.
func NbPlayerEQ(v int) predicate.Game {
	return predicate.Game(sql.FieldEQ(FieldNbPlayer, v))
}

// NbPlayerNEQ applies the NEQ predicate on the "nb_player" field.
func NbPlayerNEQ(v int) predicate.Game {
	return predicate.Game(sql.FieldNEQ(FieldNbPlayer, v))
}

// NbPlayerIn applies the In predicate on the "nb_player" field.
func NbPlayerIn(vs ...int) predicate.Game {
	return predicate.Game(sql.FieldIn(FieldNbPlayer, vs...))
}

// NbPlayerNotIn applies the NotIn predicate on the "nb_player" field.
func NbPlayerNotIn(vs ...int) predicate.Game {
	return predicate.Game(sql.FieldNotIn(FieldNbPlayer, vs...))
}

// NbPlayerGT applies the GT predicate on the "nb_player" field.
func NbPlayerGT(v int) predicate.Game {
	return predicate.Game(sql.FieldGT(FieldNbPlayer, v))
}

// NbPlayerGTE applies the GTE predicate on the "nb_player" field.
func NbPlayerGTE(v int) predicate.Game {
	return predicate.Game(sql.FieldGTE(FieldNbPlayer, v))
}

// NbPlayerLT applies the LT predicate on the "nb_player" field.
func NbPlayerLT(v int) predicate.Game {
	return predicate.Game(sql.FieldLT(FieldNbPlayer, v))
}

// NbPlayerLTE applies the LTE predicate on the "nb_player" field.
func NbPlayerLTE(v int) predicate.Game {
	return predicate.Game(sql.FieldLTE(FieldNbPlayer, v))
}

// HasResults applies the HasEdge predicate on the "results" edge.
func HasResults() predicate.Game {
	return predicate.Game(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, ResultsTable, ResultsColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasResultsWith applies the HasEdge predicate on the "results" edge with a given conditions (other predicates).
func HasResultsWith(preds ...predicate.Result) predicate.Game {
	return predicate.Game(func(s *sql.Selector) {
		step := newResultsStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.Game) predicate.Game {
	return predicate.Game(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.Game) predicate.Game {
	return predicate.Game(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Game) predicate.Game {
	return predicate.Game(sql.NotPredicates(p))
}
