export { ObjectManager, OBJECT_TYPE } from './tools/ObjectManager'
export type { ManagedObject, ManagedObjectInput, SimpleObjectInput, ObjectType, PhysicsDescriptor, HitboxShape, Piece, PieceHitbox, Vec3 } from './tools/ObjectManager'
export { ComponentLoader } from './tools/ComponentLoader'
export type { ComponentDef, MeshDef, MeshGLTF, MeshPrimitive, HitboxDef, HitboxSize, PhysicsDef, AnimationDef, WaypointAnimDef, ClipAnimDef, TextureDef, TextureAll, TexturePBR, TextureFaces } from './tools/ComponentLoader'
export { GeometryFactory } from './tools/GeometryFactory'
export type { BoxOptions, SphereOptions, CylinderOptions, ConeOptions, PlaneOptions, CircleOptions, RingOptions, TorusOptions, CapsuleOptions, PyramidOptions, LatheOptions, PolyhedronOptions, MeshOptions, Transform, MaterialParams } from './tools/GeometryFactory'
export { PhysicsWorld } from './tools/PhysicsWorld'
export type { PhysicsWorldConfig, Zone, ZoneShape } from './tools/PhysicsWorld'
export { makeZoneSphere, makeZoneBox, makeZoneCylinder } from './tools/PhysicsWorld'
export { GLTFLoader } from './tools/GLTFLoader'
export { MapLoader } from './tools/MapLoader'
export type { MapDef, MapObjectInstance, SkyDef, SkyPreset, SkyEquirect, SkyCubemap, FogDef, LightDef, AmbientLightDef, DirectionalLightDef, PointLightDef, SpotLightDef, HemisphereLightDef, ShadowDef } from './tools/MapLoader'
export { COLLISION_LAYER } from './tools/PhysicsWorld'
export { LightFactory } from './tools/LightFactory'
